apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
