"""
SSP Parser — System Security Plan → RAG-Ready JSONL

Converts Markdown-format SSPs into structured JSONL records for ChromaDB ingestion.
Each record is one "chunk": a control implementation statement, POA&M item, or
system metadata block.

Control traceability:
  PL-2    — SSP is the primary artifact being parsed; structure extraction maps to SSP schema
  MAP-2.3 — BERU limitations documented in SSP; parser captures "not implemented" statements
  MAP-4.1 — Data collection lifecycle risk: parser ONLY accepts synthetic SSPs (see _validate_source)
  SC-28   — No real client data in training corpus; synthetic SSPs from Gemini are safe by construction
  AU-3    — Every parsed chunk retains provenance (source_file, section, control_id)

3PAO question this answers:
  "Where does BERU's RAG knowledge of SSP structure come from?"
  "How do you know the SSP parser doesn't ingest real client data into training?"
"""

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional


# NIST 800-53 Rev 5 — all 20 control family codes
_CONTROL_FAMILIES = {
    "AC": "Access Control",
    "AT": "Awareness and Training",
    "AU": "Audit and Accountability",
    "CA": "Assessment, Authorization, and Monitoring",
    "CM": "Configuration Management",
    "CP": "Contingency Planning",
    "IA": "Identification and Authentication",
    "IR": "Incident Response",
    "MA": "Maintenance",
    "MP": "Media Protection",
    "PE": "Physical and Environmental Protection",
    "PL": "Planning",
    "PM": "Program Management",
    "PS": "Personnel Security",
    "PT": "Personally Identifiable Information Processing and Transparency",
    "RA": "Risk Assessment",
    "SA": "System and Services Acquisition",
    "SC": "System and Communications Protection",
    "SI": "System and Information Integrity",
    "SR": "Supply Chain Risk Management",
}

# Regex: matches "AC-2", "SI-4(a)", "CM-6 (1)" in section headers
_CONTROL_ID_RE = re.compile(
    r"\b([A-Z]{2})-(\d+)(?:\s*\((\d+)\))?\b"
)

# Regex: POA&M item header patterns
_POAM_RE = re.compile(
    r"(?:POA&M|POAM|Plan\s+of\s+Action).*?(?:Item\s+)?(\d+)",
    re.IGNORECASE,
)

# Synthetic SSP markers (Gemini-generated SSPs include one of these)
_SYNTHETIC_MARKERS = [
    "synthetic",
    "generated by gemini",
    "fictional",
    "training data",
    "do not distribute",
    "example ssp",
    "sample ssp",
]


class SSPParser:
    """
    Parse Markdown-format System Security Plans into RAG-ready JSONL chunks.

    Usage:
        parser = SSPParser()
        chunks = parser.parse_file("path/to/ssp.md")
        parser.write_jsonl(chunks, "path/to/output.jsonl")

    Each chunk is a dict suitable for ChromaDB ingestion (collection: beru-nist-800-53).
    """

    def __init__(self, enforce_synthetic: bool = True):
        """
        Args:
            enforce_synthetic: If True, reject SSPs without a synthetic marker.
                               MAP-4.1 + SC-28: no real client data in training corpus.
                               Set False only for evaluation/test runs on known-safe docs.
        """
        self.enforce_synthetic = enforce_synthetic
        self._parsed_count = 0
        self._rejected_count = 0

    def parse_file(self, path: str | Path) -> List[Dict[str, Any]]:
        """Parse a single SSP file. Returns list of chunk dicts."""
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(f"SSP file not found: {p}")
        text = p.read_text(encoding="utf-8")
        return list(self._parse_text(text, source_file=p.name))

    def parse_text(self, text: str, source_file: str = "inline") -> List[Dict[str, Any]]:
        """Parse SSP from a string. Returns list of chunk dicts."""
        return list(self._parse_text(text, source_file=source_file))

    def parse_directory(self, directory: str | Path,
                        glob: str = "*.md") -> List[Dict[str, Any]]:
        """Parse all SSP files in a directory. Returns merged list of chunks."""
        d = Path(directory)
        chunks = []
        for p in sorted(d.glob(glob)):
            try:
                chunks.extend(self.parse_file(p))
            except ValueError as e:
                # enforce_synthetic rejection — log and skip
                self._rejected_count += 1
                print(f"[SSPParser] SKIP {p.name}: {e}")
        return chunks

    def write_jsonl(self, chunks: List[Dict[str, Any]],
                    output_path: str | Path) -> int:
        """Write chunks to JSONL file. Returns number of records written."""
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            for chunk in chunks:
                f.write(json.dumps(chunk) + "\n")
        return len(chunks)

    def stats(self) -> Dict[str, int]:
        return {"parsed": self._parsed_count, "rejected": self._rejected_count}

    # ── Internal ──────────────────────────────────────────────────────────────

    def _parse_text(self, text: str, source_file: str) -> Iterator[Dict[str, Any]]:
        if self.enforce_synthetic:
            self._validate_source(text, source_file)

        system_meta = self._extract_system_metadata(text)
        sections = self._split_sections(text)

        for section_header, section_body in sections:
            chunk_type = self._classify_section(section_header, section_body)

            if chunk_type == "control_implementation":
                yield from self._parse_control_section(
                    section_header, section_body, system_meta, source_file
                )
            elif chunk_type == "poam":
                yield from self._parse_poam_section(
                    section_header, section_body, system_meta, source_file
                )
            elif chunk_type == "system_description":
                yield self._make_chunk(
                    chunk_type="system_description",
                    text=section_body.strip(),
                    control_id=None,
                    section=section_header,
                    system_meta=system_meta,
                    source_file=source_file,
                )

        self._parsed_count += 1

    def _validate_source(self, text: str, source_file: str) -> None:
        """
        Reject SSPs that don't have a synthetic marker.
        MAP-4.1: training data risk mitigated by rejecting real-client docs.
        """
        text_lower = text[:2000].lower()
        if not any(marker in text_lower for marker in _SYNTHETIC_MARKERS):
            self._rejected_count += 1
            raise ValueError(
                f"SSP '{source_file}' lacks a synthetic marker. "
                "Real client SSPs must not enter the training corpus. "
                "Add 'synthetic' or 'training data' to the document header. "
                "See beru-design-decisions.md D-005 (MAP-4.1, SC-28)."
            )

    def _extract_system_metadata(self, text: str) -> Dict[str, str]:
        """Extract top-level SSP metadata: system name, categorization, version."""
        meta: Dict[str, str] = {}

        # System name: look for "# System Name:" or "System Name:" or first H1
        name_patterns = [
            r"System\s+Name\s*[:\|]\s*(.+)",
            r"^#\s+(.+)",  # first H1 as fallback
        ]
        for pat in name_patterns:
            m = re.search(pat, text[:1000], re.MULTILINE | re.IGNORECASE)
            if m:
                meta["system_name"] = m.group(1).strip().rstrip("#").strip()
                break

        # Security categorization: FIPS 199 Low/Moderate/High
        cat_m = re.search(
            r"(?:security\s+categorization|impact\s+level)\s*[:\|]\s*(Low|Moderate|High)",
            text[:2000],
            re.IGNORECASE,
        )
        if cat_m:
            meta["categorization"] = cat_m.group(1).capitalize()

        # SSP version
        ver_m = re.search(
            r"(?:version|rev|revision)\s*[:\|]?\s*v?([\d.]+)",
            text[:1000],
            re.IGNORECASE,
        )
        if ver_m:
            meta["version"] = ver_m.group(1)

        return meta

    def _split_sections(self, text: str) -> List[tuple[str, str]]:
        """Split document into (header, body) pairs at H2/H3 boundaries."""
        # Split on ## or ### headings
        pattern = re.compile(r"^#{2,3}\s+(.+)$", re.MULTILINE)
        matches = list(pattern.finditer(text))

        if not matches:
            return [("Document", text)]

        sections = []
        for i, match in enumerate(matches):
            header = match.group(1).strip()
            start = match.end()
            end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
            body = text[start:end].strip()
            if body:
                sections.append((header, body))

        return sections

    def _classify_section(self, header: str, body: str) -> str:
        """Classify a section as control_implementation, poam, or system_description."""
        header_lower = header.lower()

        # POA&M sections — header check
        if any(kw in header_lower for kw in ["poa&m", "poam", "plan of action"]):
            return "poam"

        # POA&M sections — body content check (handles "### Item N" subsections)
        body_lower = body[:300].lower()
        if any(m in body_lower for m in [
            "weakness:", "scheduled completion:", "milestones:", "corrective action"
        ]):
            return "poam"

        # Control implementation: contains a control ID in header or has NIST control structure
        if _CONTROL_ID_RE.search(header):
            return "control_implementation"

        # Body contains control-structured content
        control_matches = _CONTROL_ID_RE.findall(body[:500])
        if len(control_matches) >= 2:
            return "control_implementation"

        # System description sections
        if any(kw in header_lower for kw in [
            "system description", "system overview", "purpose", "scope",
            "system boundary", "system categorization", "authorization boundary",
        ]):
            return "system_description"

        return "system_description"

    def _parse_control_section(
        self, header: str, body: str,
        system_meta: Dict, source_file: str
    ) -> Iterator[Dict[str, Any]]:
        """
        Parse a control implementation section.
        May contain multiple controls (e.g., an entire family section).
        Each control implementation statement becomes its own chunk.
        """
        # Try to split by individual control IDs within the body
        control_splits = self._split_by_control_id(body)

        if control_splits:
            for control_id, impl_text in control_splits:
                if impl_text.strip():
                    yield self._make_chunk(
                        chunk_type="control_implementation",
                        text=impl_text.strip(),
                        control_id=control_id,
                        section=header,
                        system_meta=system_meta,
                        source_file=source_file,
                    )
        else:
            # Whole section is one control block
            control_id_match = _CONTROL_ID_RE.search(header)
            single_ctrl_id: Optional[str] = (
                f"{control_id_match.group(1)}-{control_id_match.group(2)}"
                if control_id_match else None
            )
            yield self._make_chunk(
                chunk_type="control_implementation",
                text=body.strip(),
                control_id=single_ctrl_id,
                section=header,
                system_meta=system_meta,
                source_file=source_file,
            )

    def _split_by_control_id(
        self, text: str
    ) -> List[tuple[str, str]]:
        """Split text at control ID anchors (e.g., '### AC-2', '**AC-6**')."""
        pattern = re.compile(
            r"(?:^#{2,4}\s*|\*\*\s*)([A-Z]{2}-\d+(?:\s*\(\d+\))?)\s*(?:\*\*)?",
            re.MULTILINE,
        )
        matches = list(pattern.finditer(text))
        if not matches:
            return []

        splits = []
        for i, m in enumerate(matches):
            raw_id = m.group(1).replace(" ", "")
            # Normalize: "AC-6(1)" stays, "AC-6" stays
            control_id = re.sub(r"\((\d+)\)", r"(\1)", raw_id)
            start = m.end()
            end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
            impl_text = text[start:end].strip()
            splits.append((control_id, impl_text))

        return splits

    def _parse_poam_section(
        self, header: str, body: str,
        system_meta: Dict, source_file: str
    ) -> Iterator[Dict[str, Any]]:
        """
        Parse POA&M items. Each item becomes a separate chunk.
        POA&M structure: Item N → Control → Weakness → Scheduled Completion → Milestones
        """
        # Split on POA&M item boundaries
        item_pattern = re.compile(
            r"(?:^#{2,4}\s*(?:Item|POA&M Item)\s*(\d+)|^\*\*(?:Item|POA&M Item)\s*(\d+)\*\*)",
            re.MULTILINE | re.IGNORECASE,
        )
        matches = list(item_pattern.finditer(body))

        if matches:
            for i, m in enumerate(matches):
                item_num = m.group(1) or m.group(2) or str(i + 1)
                start = m.end()
                end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
                item_text = body[start:end].strip()

                # Extract control ID from item text
                ctrl_m = _CONTROL_ID_RE.search(item_text[:200])
                control_id = (
                    f"{ctrl_m.group(1)}-{ctrl_m.group(2)}" if ctrl_m else None
                )

                yield self._make_chunk(
                    chunk_type="poam_item",
                    text=item_text,
                    control_id=control_id,
                    section=f"POA&M Item {item_num}",
                    system_meta=system_meta,
                    source_file=source_file,
                    extra={"poam_item_number": item_num},
                )
        else:
            # Whole section is one POA&M block
            yield self._make_chunk(
                chunk_type="poam_item",
                text=body.strip(),
                control_id=None,
                section=header,
                system_meta=system_meta,
                source_file=source_file,
            )

    def _make_chunk(
        self,
        chunk_type: str,
        text: str,
        control_id: Optional[str],
        section: str,
        system_meta: Dict,
        source_file: str,
        extra: Optional[Dict] = None,
    ) -> Dict[str, Any]:
        """Build a ChromaDB-ready chunk dict."""
        chunk: Dict[str, Any] = {
            "id": self._chunk_id(text, source_file, section),
            "chunk_type": chunk_type,
            "text": text,
            "control_id": control_id,
            "control_family": self._family_name(control_id),
            "section": section,
            "source_file": source_file,
            "system_name": system_meta.get("system_name", "unknown"),
            "categorization": system_meta.get("categorization", "unknown"),
            "version": system_meta.get("version", "unknown"),
            "ingested_at": datetime.now(timezone.utc).isoformat(),
            "collection": "beru-nist-800-53",
        }
        if extra:
            chunk.update(extra)
        return chunk

    def _chunk_id(self, text: str, source_file: str, section: str) -> str:
        """Deterministic content-based ID — same content = same ID (dedup)."""
        payload = f"{source_file}:{section}:{text[:200]}"
        return hashlib.sha256(payload.encode()).hexdigest()[:16]

    def _family_name(self, control_id: Optional[str]) -> Optional[str]:
        if not control_id:
            return None
        m = re.match(r"^([A-Z]{2})", control_id)
        if m:
            return _CONTROL_FAMILIES.get(m.group(1))
        return None
