#!/usr/bin/env bash
# generate-compliance-report.sh — Generate MLOps compliance/lifecycle report
# Usage: bash tools/generate-compliance-report.sh [--full|--section data-provenance]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="${PACKAGE_DIR}/outputs"
mkdir -p "$OUTPUT_DIR"

REPORT="${OUTPUT_DIR}/mlops-compliance-report-$(date +%Y%m%d).md"
SECTION="${1:---full}"

echo "=== Generating MLOps Compliance Report ==="
echo "Output: ${REPORT}"

cat > "$REPORT" << EOF
# MLOps Compliance Report

**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Scope:** Full model lifecycle audit

---

## 1. Executive Summary

| Metric | Value |
|--------|-------|
| Models in production | $(kubectl get inferenceservice -n ml-serving 2>/dev/null | grep -c -E 'jade|katie' || echo "N/A") |
| Training data (curated) | $(find ../../GP-MODEL-OPS/1-data-pipeline/05-data-quality/curated/ -name "*.jsonl" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}' || echo "N/A") examples |
| RAG documents | $(python3 -c "import chromadb; c=chromadb.PersistentClient(path='../../GP-MODEL-OPS/2-rag-ingestion/05-ragged-data/chroma/'); print(sum(col.count() for col in c.list_collections()))" 2>/dev/null || echo "N/A") |
| Eval benchmark | $(wc -l < ../../GP-MODEL-OPS/4-eval-clarify/jade_8b_eval_suite_v1.jsonl 2>/dev/null || echo "N/A") questions |

---

## 2. Model Lineage

| Field | Value |
|-------|-------|
| Base model | meta-llama/Llama-3.2-3B-Instruct |
| Fine-tuning | LoRA (r=64, alpha=128, 4-bit) |
| Framework | Unsloth + HuggingFace Transformers |
| Serving format | GGUF (Q4_K_M) |
| Runtime | KServe + vLLM on Kubernetes |

---

## 3. Data Provenance

- **Raw corpus source count:** $(ls ../../GP-MODEL-OPS/1-data-pipeline/01-raw-data-lake/ 2>/dev/null | wc -l || echo "N/A") files
- **Curation tool:** tools/curate_corpus.py
- **Quality gates:** Format (ChatML), scope, dedup, content quality, chunk size

---

## 4. Infrastructure Security

EOF

# Check security context on ML pods
if command -v kubectl &>/dev/null; then
    echo '```' >> "$REPORT"
    for ns in ml-serving mlops; do
        echo "--- Namespace: $ns ---" >> "$REPORT"
        kubectl get pods -n "$ns" -o json 2>/dev/null | python3 -c "
import json,sys
try:
    pods = json.load(sys.stdin)['items']
    for pod in pods:
        for c in pod['spec']['containers']:
            sc = c.get('securityContext', {})
            print(f\"  {c['name']}: nonRoot={sc.get('runAsNonRoot', 'NOT SET')}, readOnly={sc.get('readOnlyRootFilesystem', 'NOT SET')}\")
except: print('  No pods found')
" >> "$REPORT"
    done
    echo '```' >> "$REPORT"
fi

cat >> "$REPORT" << 'EOF'

---

## 5. Recommendations

| Priority | Item | Status |
|----------|------|--------|
| 1 | Pipeline orchestration (KFP) | |
| 2 | Data quality gates | |
| 3 | Automated eval + promotion | |
| 4 | Model CI/CD | |
| 5 | Drift detection | |

---

*Generated by GP-Copilot 9-MLOPS-DEPLOY*
EOF

echo ""
echo "Report written to: ${REPORT}"
